import "./globals.css";
import { Montserrat } from "@next/font/google";

const montserrat = Montserrat({
  weight: ['500', '600', '700', '800', '900'],
  subsets: ["latin-ext"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Next 13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />

      <body className={`${montserrat.className} mx-32 my-12`}>
        {children}
      </body>
    </html>
  );
}
